main: hbncore.Main
version: 1.0.0
api-version: 1.18
name: hbncore
author: gooch (gurrrrrrett3)
commands:
  starter:
    description: shows starter info
    usage: /<command>
    permission: hbncore.starter
  rules:
    description: shows rules
    usage: /<command>
    permission: hbncore.rules
  giveitem:
    description: gives an item from the plugin
    usage: /<command> <item>
    permission: hbncore.giveitem